<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Google.Apis" Version="1.71.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.71.0" />
    <PackageReference Include="Google.Apis.Core" Version="1.71.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.70.0.3833" />
    <PackageReference Include="Google_GenerativeAI" Version="3.2.0" />
  </ItemGroup>

</Project>
